# Generated by Django 5.2
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(name="Classroom", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=100, unique=True))], options={"ordering": ["name"]}),
        migrations.CreateModel(name="Student", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=100)), ("active", models.BooleanField(default=True)), ("classroom", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="students", to="attendance.classroom"))], options={"ordering": ["name", "id"]}),
        migrations.CreateModel(name="AttendanceSession", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("date", models.DateField()), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("classroom", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sessions", to="attendance.classroom"))], options={"ordering": ["-date"]}),
        migrations.CreateModel(name="AttendanceRecord", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("status", models.CharField(choices=[("present", "出席"), ("absent", "缺席")], max_length=7)), ("session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="records", to="attendance.attendancesession")), ("student", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="attendance_records", to="attendance.student"))], options={"ordering": ["session__date", "student__name"]}),
        migrations.AddConstraint(model_name="student", constraint=models.UniqueConstraint(fields=("classroom", "name"), name="unique_student_name_per_class")),
        migrations.AddConstraint(model_name="attendancesession", constraint=models.UniqueConstraint(fields=("classroom", "date"), name="unique_classroom_date")),
        migrations.AddConstraint(model_name="attendancerecord", constraint=models.UniqueConstraint(fields=("session", "student"), name="unique_session_student")),
    ]
